INSERT INTO MONEY_BILLS (ID, ACTIVE, CREATED_AT, UPDATED_AT, LABEL, VALUE) 
VALUES (RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), '5 reais', 5),
(RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), '10 reais', 10),
(RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), '20 reais', 20),
(RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), '50 reais', 50),
(RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), '100 reais', 100);
